@startuml
left to right direction
skinparam packageStyle rectangle
skinparam usecase {
    BackgroundColor #F8F9FA
    BorderColor #00509E
    ArrowColor #00509E
}
skinparam actor {
    BackgroundColor #E6F2FF
    BorderColor #00509E
}

' ==========================================
' ĐỊNH NGHĨA CÁC ACTOR (VAI TRÒ)
' ==========================================

actor "User\n(Người dùng)" as User
actor "Admin\n(Quản trị viên)" as Admin
actor "Guest\n(Khách)" as Guest

  Admin -[hidden]down- User
  User -[hidden]down- Guest


' Thiết lập tính kế thừa: 
' User kế thừa Guest. Instructor và Admin kế thừa User.
User <|-- Admin
Guest <|-- User

' ==========================================
' ĐỊNH NGHĨA HỆ THỐNG VÀ CÁC USE CASE
' ==========================================
rectangle "Hệ thống PhysicMUT" {

    package "Khám phá & Học tập (Public)" {
        ' usecase "Đăng ký / Đăng nhập" as UC_Auth
        usecase "Xem danh sách các mô hình 3D" as UC_ViewModel
        usecase "Xem chi tiết từng mô hình 3D" as UC_ViewDetail
        usecase "Đọc lý thuyết, bài tập mẫu" as UC_ViewTheory
        usecase "Luyện tập" as UC_ViewExercise
        usecase "Tương tác mô phỏng 3D" as UC_Interact3D
        usecase "Hỏi AI Bot" as UC_AskBot
    }

    package "Xác thực người dùng" {
        usecase "Đăng ký / Đăng nhập" as UC_Auth
    }


    package "Quản trị Hệ thống (Admin)" {
        usecase "Quản lý Admin" as UC_Admin
        usecase "Quản lý vai trò" as UC_ManageRoles
        usecase "Quản lý người dùng" as UC_ManageUsers
        usecase "Quản lý mô hình 3D" as UC_ManageModels
        usecase "Quản lý lý thuyết, bài tập mẫu, bài tập" as UC_ManageContent
    }
}

' ==========================================
' GÁN QUYỀN (LIÊN KẾT ACTOR VỚI USE CASE)
' ==========================================

' User
' User --> UC_Auth    
User --> UC_ViewModel
User --> UC_ViewDetail
User --> UC_ViewTheory
User --> UC_ViewExercise
User --> UC_Interact3D
User --> UC_AskBot

' Admin
Admin --> UC_Admin
Admin --> UC_ManageRoles
Admin --> UC_ManageUsers
Admin --> UC_ManageModels
Admin --> UC_ManageContent

' Guest
Guest --> UC_Auth

@enduml