# ID của dự án
sonar.host.url=https://sonarcloud.io
sonar.organization=tanlocdev04
sonar.projectKey=TanLoc-DEV04_PhysicMUT
sonar.projectName=PhysicMUT-be
# Đường dẫn tới source code cần quét
sonar.sources=src

# Loại trừ các thư mục không cần quét
sonar.exclusions=**/node_modules/**, **/*.test.ts, src/scripts/**, dist/**, prisma/migrations/**

# Cấu hình quét TypeScript
# sonar.language=ts
sonar.sourceEncoding=UTF-8

# Nếu bạn có chạy Jest để lấy Coverage (Mức độ 1), chỉ đường dẫn vào đây
sonar.javascript.lcov.reportPaths=coverage/lcov.info
