name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd PhysicMUT-be
          npm install

      - name: Build project (TypeScript Check)
        run: |
          cd PhysicMUT-be
          npm run build

      - name: Run Integration Tests
        run: |
          cd PhysicMUT-be
          npm test

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
        with:
          args: >
            -Dsonar.projectBaseDir=PhysicMUT-be
            -Dsonar.javascript.lcov.reportPaths=PhysicMUT-be/coverage/lcov.info
            -Dsonar.qualitygate.wait=false
